const repos = [
  'https://github.com/Peco1503/01-basic-html',
  'https://github.com/marcopod/01-basic-html',
  'https://github.com/Bdelas777/WizelineClass',
  'https://github.com/JulioEmmmanuel/web-activities',
  'https://github.com/oznerx/Actividad-Web-1-HTML',
  'https://github.com/adrian-rmz/a00830640-web',
  'https://github.com/RoJosGaRis/01-basic',
  // 'https://github.com/Diegogtz03/HTML-class-exercises',
  'https://github.com/pedroalonsoms/html-clases',
  'https://github.com/sofia-cantu/WebLearning',
  'https://github.com/a01721732/TC3005B_A01721732',
  'https://github.com/A01411926/rickandmorty',
  'https://github.com/A01411926/6to-semestre',
  'https://github.com/CaroGzzLeal/TC3005B_Web',
  'https://github.com/JoseCSG/html_clases',
  'https://github.com/Fausto420/A01412004moduloweb',
  'https://github.com/Cherry-Ayala/WebTC3005B.101',
  'https://github.com/Lebrijay02/01-basic-html',
  'https://github.com/Lebrijay02/04-nestjs-rick-and-morty',
  'https://github.com/GabrielRuizMiller/a00835179_html_basico',
  'https://github.com/GabrielRuizMiller/03-profile',
  'https://github.com/GabrielRuizMiller/04-nextjs-rick-and-morty',
  'https://github.com/Felipegonac0/ActividadesWeb',
  'https://github.com/KrakenDominguezz/Actividades_Web',
  'https://github.com/EduardodeValle/01-basic-html',
  'https://github.com/ChalkyMuffin/HTML-basico',
  'https://github.com/rviz/WebAvanzado6to',
  'https://github.com/TheNullPower/TC3005B-Web',
  'https://github.com/Eugenio2002-tec/Eugenio-web',
  'https://github.com/Hugoalv79/WizelineWebClass',
  'https://github.com/lapl13/clase-web',
  'https://github.com/lapl13/04-nextjs-rick-and-morty.git',
  'https://github.com/Valenriquez/XploreTailwindCSS',
  'https://github.com/SofiRegiM/rick-morty',
  // 'https://github.com/AlexMendozaPrado/04-nestjs-rick-and-morty',
];

module.exports = { repos };
